// Generated by https://quicktype.io

export interface WizardResponse {
  message: string;
  agency_wizard: AgencyWizard;
}

export interface AgencyWizard {
  id: number;
  workspace_id: number;
  seo: SEO;
  website_details: WebsiteDetails;
  services: Service[];
  service_benefits: ServiceBenefit[];
  testimonials: Service[];
  contact: Contact;
  preview_ui: string;
  created_at: Date;
}

export interface Contact {
  address: Address;
  introduction: Introduction;
  about: About;
  help: Help;
}

export interface About {
  about_desc: string;
  about_cta: number;
}

export interface Address {
  businessName: string;
  address1: string;
  address2: string;
  email: string;
  phone: string;
  city: string;
  state: string;
  country: string;
}

export interface Help {
  help_headline: null;
  help_desc: null;
  help_cta: null;
}

export interface Introduction {
  intro_headline: string;
  intro_desc: string;
  intro_cta: number;
}

export interface SEO {
  title: null;
  desc: null;
  image: null;
}

export interface Service {
  id: number;
  name: string;
  description: string;
  metaImage: null | string;
  created_at: Date;
}

export interface ServiceBenefit {
  id: number;
  name: string;
  description: string;
  metaImage: null | string;
  created_at: Date;
}

export interface WebsiteDetails {
  agencyName: string;
  contactNotification: string;
  url: string;
  customJavascript: null;
  logo: string;
  favIcon: string;
}
